project_id = "ulbjqdwnmjvmsrjrball"

[functions.ping-supabase]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.process-anamnesis-ocr]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
